name: Node.js CI

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Debug:List directory contents
        run: ls -la

      - name: Create production-build ZIP
        run: |
          cd dist
          zip -r ../production-build.zip .

      - name: Upload production-build ZIP
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: production-build.zip
