name: Node.js CI

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Debug:List directory contents
        run: ls -la

      - name: Verify dist directory exists
        run: |
          if [ ! -d "dist" ]; then
            echo "Dist directory not found!"
            exit 1
          fi

      - name: Create build artifact ZIP
        run: zip -r build-artifact.zip dist/

      - name: Upload build artifact ZIP
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: build-artifact.zip
